language: go
go:
- '1.12.x'

cache:
  directories:
    - $GOPATH/pkg/mod
    - $HOME/.cache/go-build

env:
  - GO111MODULE=on

install: true

script:
  - travis_wait go test -v -timeout 20m -race -covermode=atomic -coverprofile=coverage.txt .

after_success:
  - bash <(curl -s https://codecov.io/bash)