language: go
go:
- '1.11.x'

cache:
  directories:
    - $GOPATH/src/gx

install:
  - go get github.com/whyrusleeping/gx
  - go get github.com/whyrusleeping/gx-go
  - gx --verbose install --global
  - gx-go rewrite

script:
  - go test -v -race -covermode=atomic -coverprofile=coverage.txt .

after_success:
  - bash <(curl -s https://codecov.io/bash)